### ISSUE TITLE
Status page doesn't update anymore when a Stratum 1 is down

### ISSUE THREAD

**Issue by bedroge** [EESSI/status-page#1]
While updating and rebooting some of the Stratum 1 servers today, I noticed that the status page doesn't get updated anymore while a Stratum 1 is unavailable. Not sure if it's an issue with the status page itself or with the scraper.

**Comment by terjekv** [comment]
The scraper's URL check timeout kills the threader. Good work in finding out, thanks!

**Comment by terjekv** [comment]
I have an updated scraper and status page generator that works, but I'm going to do some more testing. Also, we got a new `data` repo that isn't correct on rug-nl.stratum1, is that expected?

**Comment by bedroge** [comment]
Yes, I've added that repo to the Stratum 0 yesterday:
https://github.com/EESSI/filesystem-layer/pull/119
To make sure that it works properly (and I could access it from a client), I've also made it available on the RUG S1, but not on the other ones yet.

**Comment by terjekv** [comment]
Hmm, so it should return OK for rug-nl, but not others. Right.

**Comment by terjekv** [comment]
Verified resolved in https://github.com/EESSI/status-page/commit/734144b5e35ea8687e35ccf9a598be7c3d06210d.
